export const biroPerjalananData = [
	{
		id: "bp1",
		name: "Smart Tour Purwokerto",
		category: "Biro Perjalanan",
		address:
			"Jl. Patriot No.38, Gandasuli, Karangpucung, Kec. Purwokerto Selatan",
		rating: 4.9,
		image: require("../../assets/biroPerjalanan/smart-tour logo.jpg"),
		description: "Paket wisata keliling Banyumas",
		openHours: "Senin - Sabtu, 09:00 – 17:00",
		phone: "0857-2649-2521",
		price: "Rp 250.000 - Rp 395.000",
		facilities: ["Fasilitas bus pariwisata", "Tiket Masuk", "Dokumentasi"],
		coordinate: {
			latitude: -7.4383769712522545,
			longitude: 109.23930512883533,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/biroPerjalanan/smart1.jpg")],
	},
	{
		id: "bp2",
		name: "Diary Tour and Travel",
		category: "Biro Perjalanan",
		address: "Sapphire Regency No.D113, Kober, Purwokerto Barat",
		rating: 5.0,
		image: require("../../assets/biroPerjalanan/diary-tourlogo.jpg"),
		description:
			"Paket Wisata Tour ke selulruh Indonesia dan ke beberapa negara di ASEAN",
		openHours: "Senin - Sabtu, 08:00 – 17:00",
		phone: "0815-5355-1551",
		price: "Rp 40.000 - Rp 135.000",
		facilities: ["Fasilitas bus pariwisata", "Tiket Masuk", "Dokumentasi"],
		coordinate: {
			latitude: -7.4146514544986335,
			longitude: 109.21319520000002,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [
			require("../../assets/biroPerjalanan/diary-tourlogo.jpg"),
			require("../../assets/biroPerjalanan/diary1.jpg"),
		],
	},
	{
		id: "bp3",
		name: "FAW Tour & Travel",
		category: "Biro Perjalanan",
		address:
			"Pasar Centra Komoditi, Kios Blok B-5, Dusun II, Pernasidi, Kec. Cilongok",
		rating: 4.5,
		image: require("../../assets/biroPerjalanan/faw-tour logo.jpg"),
		description: "Agen ini melayani berbagai kebutuhan perjalanan dan wisata",
		openHours: "Senin - Sabtu, 08:00 – 17:00",
		phone: "0852-9144-4555",
		price: "Rp -",
		facilities: [
			"Antar-jemput",
			"Tiket Wisata",
			"Pemandu Wisata",
			"Pengelolaan BBM dan parkir",
		],
		coordinate: {
			latitude: -7.4002930671776905,
			longitude: 109.1313229,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/biroPerjalanan/faw-tour logo.jpg")],
	},
	{
		id: "bp4",
		name: "Mitra Amanah Tour & Travel",
		category: "Biro Perjalanan",
		address: "Jl. Kaliputih, Purwokerto Wetan, Kec. Purwokerto Timur",
		rating: 4.5,
		image: require("../../assets/biroPerjalanan/mitra-amanah logo.jpg"),
		description:
			"Penyediaan jasa perjalanan mulai dari private trip, open trip, study tour, dll",
		openHours: "Senin - Sabtu, 09:00 – 17:00",
		phone: "0821-3513-1818",
		price: "Rp 0",
		facilities: ["-"],
		coordinate: {
			latitude: -7.425955636701419,
			longitude: 109.25545032698791,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/biroPerjalanan/mitra-amanah logo.jpg")],
	},
	{
		id: "bp5",
		name: "Continue Tour & MICE Organizer",
		category: "Biro Perjalanan",
		address: "Jl. Pahlawan, Tanjung, Kec. Purwokerto Selatan",
		rating: 5.0,
		image: require("../../assets/biroPerjalanan/continue-tour logo.png"),
		description: "Penyediaan jasa perjalanan",
		openHours: "Senin - Minggu, 08:00 – 00:00",
		phone: "0858-0062-0103 ",
		price: "Rp 0",
		facilities: [
			"Paket wisata insentif",
			"kegiatan team building",
			"Pemandu Wisata",
			"Souvenir",
		],
		coordinate: {
			latitude: -7.435146892325748,
			longitude: 109.22149928650605,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/biroPerjalanan/continue-tour logo.png")],
	},
];

export default biroPerjalananData;