export const desaWisataData = [
	{
		id: "dw1",
		name: "Desa Wisata Pekunden",
		category: "Desa Wisata",
		address: "Jl. Jaya Sirayu No.71, Pekunden Tengah, Pekunden",
		rating: 4.8,
		image: require("../../assets/desaWisata/pekunden logo.jpg"),
		description: "Desa wisata kreatif berbasis budaya dan edukasi.",
		openHours: "Senin - Minggu, 09:00 – 16:00",
		phone: "0896-5402-0934 ",
		price: "Rp 20.000 - Rp 25.000",
		facilities: [
			"Balai Pertemuan",
			"Area WiFi",
			"Mushola",
			"Paket Wisata live-in",
		],
		coordinate: {
			latitude: -7.5133235245830186,
			longitude: 109.28906405767069,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/desaWisata/pekunden1.jpeg"), require("../../assets/desaWisata/pekunden3.jpg")],
	},
	{
		id: "dw2",
		name: "Desa Wisata Kemutug Lor",
		category: "Desa Wisata",
		address: "Desa Kemutug Lor, Kec. Baturraden, Kabupaten Banyumas",
		rating: 4.8,
		image: require("../../assets/desaWisata/Desa-Kemutug-Lor.jpg"),
		description:
			"Desa wisata di Kecamatan Baturraden dengan potensi alam, budaya, outbound, dan area selfie/spot foto tepi hutan/spot menarik lainnya.",
		openHours: "Setiap hari, 07:00 - 17:00",
		phone: "082187283138",
		price: "Rp 10.000 - Rp 25.000",
		facilities: [
			"Embung Jelita",
			"Curug Pinang",
			"Parkir Luas",
			"Homestay",
			"Kuliner Khas",
			"Edukasi kerajinan ecoprint",
		],
		coordinate: {
			latitude: -7.286417999999999,
			longitude: 109.2266564,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/desaWisata/kemutug1.jpg"), require("../../assets/desaWisata/kemutug2.jpg")],
	},
	{
		id: "dw3",
		name: "Desa Wisata Cirahab",
		category: "Desa Wisata",
		address: "Area Hutan Cirahab, Kec. Lumbir, Kabupaten Banyumas",
		rating: 4.8,
		image: require("../../assets/desaWisata/cirahab.webp"),
		description:
			"Desa wisata berbasis alam di kawasan hutan Cirahab, terkenal dengan Curug Penganten, Watu Amba, dan petilasan leluhur.",
		openHours: "Setiap hari, 07:00 – 17:00",
		phone: "081234567890",
		price: "±Rp 10.000",
		facilities: ["Homestay"],
		coordinate: {
			latitude: -7.472787899999998,
			longitude: 109.0274877,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/desaWisata/cirahab1.jpg"), require("../../assets/desaWisata/cirahab2.jpg")],
	},
	{
		id: "dw4",
		name: "Desa Wisata Petahunan",
		category: "Desa Wisata",
		address: "Hutan Petahunan, Kec. Pekuncen, Kabupaten Banyumas",
		rating: 4.8,
		image: require("../../assets/desaWisata/petahunan.jpg"),
		description:
			"Wisata alam dengan banyak curug/kontur alam serta petilasan, cocok untuk yang suka eksplorasi alam.",
		openHours: "-",
		phone: "082314638895 ",
		price: "Rp 75.000 – Rp 200.000",
		facilities: ["-"],
		coordinate: {
			latitude: -7.3667631,
			longitude: 109.0364038,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/desaWisata/petahunan1.jpg"), require("../../assets/desaWisata/petahunan2.jpg")],
	},
];

export default desaWisataData;
