export const kulinerData = [
	{
		id: "kl1",
		name: "Waroenk Ora Umum",
		category: "Kuliner",
		address: "Jl. DR. Soeparno No.98, Arcawinangun, Kec. Purwokerto Timur",
		rating: 4.3,
		image: require("../../assets/kuliner/ora-umum.jpg"),
		description:
			"Waroenk Ora Umum merupakan salah satu kafe unik di Purwokerto yang menawarkan suasana santai dengan konsep tempat nongkrong yang sederhana namun nyaman.",
		openHours: "24 Jam",
		phone: "0811-2773-333",
		price: "Rp 9.000 - Rp 33.000",
		facilities: [
			"Wi-Fi",
			"Area Indoor & Outdoor",
			"Mushola",
			"Toilet",
			"Parkir",
			"Charging Area",
		],
		coordinate: {
			latitude: -7.415274884196986,
			longitude: 109.25417302336196,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/kuliner/ora umum1.jpg"), require("../../assets/kuliner/ora umum2.jpg")],
	},
	{
		id: "kl2",
		name: "Waroeng Spesial Sambal (SS) Purwokerto GOR",
		category: "Kuliner",
		address:
			"Jl. Gelora Indah 2, Mangunjaya, Purwokerto Lor, Kec. Purwokerto Timur",
		rating: 4.4,
		image: require("../../assets/kuliner/spesial-sambal.jpg"),
		description:
			"Waroeng Spesial Sambal SS adalah restoran lokal yang fokus pada hidangan pedas khas Indonesia dengan berbagai macam sambal sebagai daya tarik utamanya.",
		openHours: "Setiap Hari, 10:00 - 22:00",
		phone: "0856-2575-039",
		price: "Rp 25.000 – Rp 30.000",
		facilities: ["Tempat Parkir", "Mushola", "Toilet", "Smooking Area"],
		coordinate: {
			latitude: -7.416361855799211,
			longitude: 109.2539498034558,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/kuliner/ss1.jpg")],
	},
	{
		id: "kl3",
		name: "Warung Kopi Sepuran",
		category: "Kuliner",
		address: "Jl. Bayur No.3, Dusun III, Kebocoran, Kec. Kedungbanteng",
		rating: 4.6,
		image: require("../../assets/kuliner/kopi1.jpg"),
		description:
			"Warung kopi dengan konsep santai dan suasana yang cukup ramai oleh pengunjung.",
		openHours: "Setiap Hari, 09:00 - 21:00",
		phone: "0812-4953-9587",
		price: "Rp 10.000 – Rp 20.000",
		facilities: ["Parkir", "Toilet", "Tempat Ibadah"],
		coordinate: {
			latitude: -7.402157025473218,
			longitude: 109.20897427116468,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/kuliner/kopi-sepuran.jpg"), require("../../assets/kuliner/kopi2.jpg")],
	},
	{
		id: "kl4",
		name: "Society Coffee House",
		category: "Kuliner",
		address: "Jl. Prof. Dr. Suharso No.9B, Arcawinangun, Kec. Purwokerto Timur",
		rating: 4.6,
		image: require("../../assets/kuliner/society.jpg"),
		description:
			"Society Coffee House adalah salah satu kafe paling populer dan sering dikunjungi di Purwokerto, dikenal dengan desain interiornya yang modern, estetik, dan instagrammable.",
		openHours: "Setiap Hari, 09:00 – 23:00",
		phone: "0811-2821-168",
		price: "Rp 20.000 - Rp 50.000",
		facilities: [
			"Mushola",
			"Parkir",
			"Smooking Area & No smoking area",
			"Wi-Fi",
		],
		coordinate: {
			latitude: -7.4176002290162195,
			longitude: 109.25217017116466,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/kuliner/society1.jpg"), require("../../assets/kuliner/society2.jpg")],
	},
	{
		id: "kl5",
		name: "Warung Lik Chip Tepi Sawah",
		category: "Kuliner",
		address: "Windusara, Karangklesem, Kec. Purwokerto Selatan",
		rating: 4.1,
		image: require("../../assets/kuliner/lik-chip.jpg"),
		description:
			"Lik Chip Tepi Sawah adalah rumah makan dengan nuansa alam tepi sawah yang syahdu — menawarkan pengalaman makan di lingkungan hijau dan tenang serta pemandangan sawah yang menenangkan.",
		openHours: "Setiap Hari, 10:00 – 21:00",
		phone: "0878-4273-9793 ",
		price: "Rp 25.000 - Rp 50.000",
		facilities: ["Area Lesehan", "Tempat Parkir", "Mushola"],
		coordinate: {
			latitude: -7.438975093656026,
			longitude: 109.24485792883534,
			latitudeDelta: 0.01,
			longitudeDelta: 0.01,
		},
		images: [require("../../assets/kuliner/likchip1.png"), require("../../assets/kuliner/lik-chip.jpg")],
	},
];

export default kulinerData;
