export const eventData = [
	{
		id: 1,
		name: "Bazar Pakaian Terbesar Se-Banyumas",
		address: "Ex Moro Mall Purwokerto (EXPO EXMORO)",
		openHours: "Kamis - Rabu, 09:00 - 22:00",
		category: "Event",
		price: "Rp - (Gratis)",
		image: require("../../assets/assets-event1.jpeg"),
		description: "Bazar pakaian terbesar se-Banyumas dengan berbagai band.",
	},
	{
		id: 2,
		name: "Pagelaran Wayang Kulit Gagrag Banyumas",
		address: "Menara Pandang Teratai Purwokerto",
		openHours: "Sabtu, 13:00 - 17:30 & 19:00 - 23:30",
		category: "Event",
		price: "Rp - (Gratis)",
		image: require("../../assets/assets-event2.jpeg"),
		description: "Pagelaran wayang kulit Gagrag Banyumas dalam rangka Hari Wayang Nasional.",
	},
	{
		id: 3,
		name: "Banyumas Gamelan Festival",
		address: "Taman Sari Kec.Banyumas",
		openHours: "25 April 2026, 08:00 - selesai",
		category: "Event",
		price: "Rp - (Gratis)",
		image: require("../../assets/assets-event3.jpeg"),
		description: "Festival musik tradisional Banyumas dengan permainan gamelan.",
	},
];
